image: archlinux
packages:
  - python-poetry
  - postgresql
sources:
  - https://git.sr.ht/~alanorth/dspace-statistics-api
tasks:
  - setup: |
      id
      psql --version
      sudo su - postgres -c "initdb --locale en_US.UTF-8 -E UTF8 -D '/var/lib/postgres/data'"
      sudo systemctl start postgresql
      createuser -U postgres dspacestatistics
      psql -U postgres -c "ALTER USER dspacestatistics WITH PASSWORD 'dspacestatistics'"
      createdb -U postgres -O dspacestatistics --encoding=UNICODE dspacestatistics
      cd dspace-statistics-api
      psql -U postgres -d dspacestatistics < tests/dspacestatistics.sql
      poetry install --no-root
  - test: |
      cd dspace-statistics-api
      poetry run pytest
