dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
jobs:
  allow_failures:
    - python: "3.8-dev"
addons:
  postgresql: "10"
before_script:
  - psql --version
  - createuser -U postgres dspacestatistics
  - psql -U postgres -c "ALTER USER dspacestatistics WITH PASSWORD 'dspacestatistics'"
  - createdb -U postgres -O dspacestatistics --encoding=UNICODE dspacestatistics
  - psql -U postgres -d dspacestatistics < tests/dspacestatistics.sql
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
script: pytest

# vim: ts=2 sw=2 et
