image: archlinux
packages:
  - python-pipenv
  - postgresql
sources:
  - https://git.sr.ht/~alanorth/dspace-statistics-api
tasks:
  - setup: |
      id
      psql --version
      sudo su - postgres -c "initdb --locale en_US.UTF-8 -E UTF8 -D '/var/lib/postgres/data'"
      sudo systemctl start postgresql
      createuser -U postgres dspacestatistics
      psql -U postgres -c "ALTER USER dspacestatistics WITH PASSWORD 'dspacestatistics'"
      createdb -U postgres -O dspacestatistics --encoding=UNICODE dspacestatistics
      psql -U postgres -d dspacestatistics < tests/dspacestatistics.sql
      cd dspace-statistics-api
      pipenv install --dev
  - test: |
      cd dspace-statistics-api
      pipenv run pytest
